apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sql-creds
  namespace: tripinsights-backend
data:
  sql-user: c3FsYWRtaW5sVHQ5MjMzCg==
  sql-password: akIwaHE5WWQyCg==
  sql-server: c3Fsc2VydmVybHR0OTIzMy5kYXRhYmFzZS53aW5kb3dzLm5ldAo=
  sql-dbname: bXlkcml2aW5nREIK