# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: sql-creds
#   namespace: tripinsights-backend
# data:
#   sql-user: c3FsYWRtaW5sVHQ5MjMzCg==
#   sql-password: akIwaHE5WWQyCg==
#   sql-server: c3Fsc2VydmVybHR0OTIzMy5kYXRhYmFzZS53aW5kb3dzLm5ldAo=
#   sql-dbname: bXlkcml2aW5nREIK

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tripinsights-azure-kvname-user-msi
  namespace: tripinsights-backend
spec:
  provider: azure
  secretObjects:
  - secretName: sql-keyvault-secrets
    data:
    - key: sql-db
      objectName: SQL-DB
    - key: sql-server
      objectName: SQL-SERVER
    - key: sql-user
      objectName: SQL-USER
    - key: sql-password
      objectName: SQL-PASSWORD
    type: Opaque
  parameters:
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 7e991a89-8eb5-426b-9301-83be71f19afb
    keyvaultName: AKSOpenHackVault
    objects:  |
      array:
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
    tenantId: 395d5677-3342-49b7-bb2d-44785c2ca83b