apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-backend-user-java-deployment
  namespace: tripinsights-backend
  labels:
    app: tripinsights-backend-user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights-backend-user-java
  template:
    metadata:
      labels:
        app: tripinsights-backend-user-java
    spec:
      containers:
      - name: user-java
        image: registryltt9233.azurecr.io/jordanbean/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: CONFIG_FILES_PATH
          value: /mnt/secrets-store
        - name: CREDENTIAL_METHOD
          value: username_and_password
        volumeMounts:
        - name: tripinsights-azure-secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: tripinsights-azure-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripinsights-azure-kvname-user-msi"

---

apiVersion: v1
kind: Service
metadata:
  name: tripinsights-backend-user-java-service
  namespace: tripinsights-backend
spec:
  selector:
    app: tripinsights-backend-user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripinsights-backend-user-java-ingress
  namespace: tripinsights-backend
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aks-tripinsights-rjb-secure.0c5da0aa7dac45c783b5.westus2.aksapp.io
    http:
      paths:
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: tripinsights-backend-user-java-service
            port:
              number: 80